
#ifndef JX_ERROR_CODE_H
#define JX_ERROR_CODE_H

#include <optional>
#include <string>


enum class ErrorCode
{
    NO_ERROR,

    EXCEPTION_MANAGER_NOT_KEY_IN_OBJECT,

    KEY_MAPPER_KEY_STR_REPEAT,

    MANAGER__ROOT_NOT_EMPTY,
    MANAGER__ROOT_NOT_OBJECT,
    MANAGER__EMPTY,
    MANAGER__NOT_KEY_IN_OBJECT,
    MANAGER__IMPROPER_PATH,
    MANAGER__INDEX_OUT_OF_ARRAY,
    MANAGER__NODE_NOT_ARRAY,
    MANAGER__NODE_NOT_OBJECT,

    PREPARSER_STRING_ERROR,

    JSON_PREPARSER_UNKNOWN_SYMBOL,

    JSON_VALIDATOR__BRACKET_CURLY,
    JSON_VALIDATOR__BRACKET_SQUARE,
    JSON_VALIDATOR__IMPROPER_BEGIN,
    JSON_VALIDATOR__IMPROPER_END,
    JSON_VALIDATOR__AFTER_COMMA,
    JSON_VALIDATOR__AFTER_COLON,
    JSON_VALIDATOR__AFTER_CURLY_CLOSE,
    JSON_VALIDATOR__AFTER_CURLY_OPEN,
    JSON_VALIDATOR__AFTER_BOOL,
    JSON_VALIDATOR__AFTER_DOUBLE,
    JSON_VALIDATOR__AFTER_INT,
    JSON_VALIDATOR__AFTER_SQUARE_CLOSE,
    JSON_VALIDATOR__AFTER_SQUARE_OPEN,
    JSON_VALIDATOR__AFTER_STRING,

    XML_PARSER_TOKENS_NO_TOKENS,
    XML_PARSER_TOKENS_DECLARATION,
    XML_PARSER_TOKENS_INVALID_BEGIN,
    XML_PARSER_TOKENS_INVALID_END,
    XML_PARSER_TOKENS_OPEN_ANGLE,
    XML_PARSER_TOKENS_CLOSE_ANGLE,
    XML_PARSER_TOKENS_SLASH,
    XML_PARSER_TOKENS_QUESTION,
    XML_PARSER_TOKENS_DATA_STR,
    XML_PARSER_TOKENS_DATA_STR_QUOTA,
    XML_PARSER_TOKENS_EQUAL,

    XML_PREPARSER_STRING_ERROR,

    XML_VALIDATOR_DECLARATION_NOT_START,
    XML_VALIDATOR_MISMATCHED_TAG,
};


class Error
{
public:
    Error(ErrorCode, std::optional<std::string> info = std::nullopt);

    ErrorCode getCode() const;
    std::string getDetails() const;

private:
    std::optional<std::string> details;
    ErrorCode errorCode;
};

#endif

