
#ifndef JX_ERROR_CODE_H
#define JX_ERROR_CODE_H

#include <optional>
#include <string>


enum class ErrorCode
{
    NO_ERROR,

    EXCEPTION_MANAGER_NOT_KEY_IN_OBJECT,

    KEY_MAPPER_KEY_STR_REPEAT,

    MANAGER_ROOT_NOT_EMPTY,
    MANAGER_ROOT_NOT_OBJECT,
    MANAGER_EMPTY,
    MANAGER_NOT_KEY_IN_OBJECT,
    MANAGER_IMPROPER_PATH,
    MANAGER_INDEX_OUT_OF_ARRAY,
    MANAGER_NODE_NOT_ARRAY,
    MANAGER_NODE_NOT_OBJECT,

    PREPARSER_STRING_ERROR,

    JSON_PREPARSER_UNKNOWN_SYMBOL,

    JSON_VALIDATOR_BRACKET_CURLY,
    JSON_VALIDATOR_BRACKET_SQUARE,
    JSON_VALIDATOR_IMPROPER_BEGIN,
    JSON_VALIDATOR_IMPROPER_END,
    JSON_VALIDATOR_AFTER_COMMA,
    JSON_VALIDATOR_AFTER_COLON,
    JSON_VALIDATOR_AFTER_CURLY_CLOSE,
    JSON_VALIDATOR_AFTER_CURLY_OPEN,
    JSON_VALIDATOR_AFTER_BOOL,
    JSON_VALIDATOR_AFTER_DOUBLE,
    JSON_VALIDATOR_AFTER_INT,
    JSON_VALIDATOR_AFTER_SQUARE_CLOSE,
    JSON_VALIDATOR_AFTER_SQUARE_OPEN,
    JSON_VALIDATOR_AFTER_STRING,

    XML_PARSER_TOKENS_NO_TOKENS,
    XML_PARSER_TOKENS_DECLARATION,
    XML_PARSER_TOKENS_INVALID_BEGIN,
    XML_PARSER_TOKENS_INVALID_END,
    XML_PARSER_TOKENS_OPEN_ANGLE,
    XML_PARSER_TOKENS_CLOSE_ANGLE,
    XML_PARSER_TOKENS_SLASH,
    XML_PARSER_TOKENS_QUESTION,
    XML_PARSER_TOKENS_DATA_STR,
    XML_PARSER_TOKENS_DATA_STR_QUOTA,

    XML_PREPARSER_STRING_ERROR,

    XML_VALIDATOR_ATTR,
    XML_VALIDATOR_DECLARATION_NOT_START,
    XML_VALIDATOR_MISMATCHED_TAG,
    XML_VALIDATOR_TAG_OPEN_ATTR,
};


class Error
{
public:
    Error(ErrorCode, std::optional<std::string> info = std::nullopt);

    ErrorCode getCode() const;
    std::string getDetails() const;

private:
    std::optional<std::string> details;
    ErrorCode errorCode;
};

#endif

